### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by AnkoBG** [thewiffedshot/KEKChat#8]
Here is the todo list as of 15.04.19, new and completed tasks will be added here for reference
- [x] Move JS to the end of html
- [x] Double website speed(excluded unnecessary js and css references)
- [x] Chat: Request and load only new chat messages
- [ ] Fix creation of double records in DB when posting a meme for sale in the marketplace
- [ ] Maybe use SignalR for chat?(we haven't decided yet)
- [ ] Add different chat rooms and ability to create ones
- [ ] Add DM's (an extension to chat rooms)
